# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='part',
            name='name',
        ),
        migrations.RemoveField(
            model_name='part',
            name='short_name',
        ),
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judge',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
