# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_auto_20171102_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=15)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Problem')),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='judge',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
