# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_auto_20171102_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
