# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_auto_20171109_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestqueue',
            name='profile',
        ),
        migrations.DeleteModel(
            name='RequestQueue',
        ),
    ]
