# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_auto_20171109_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='solved_list',
            field=models.ManyToManyField(blank=True, to='progress.Problem'),
        ),
    ]
