# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_auto_20171109_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.UserProfile')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.Problem')),
            ],
        ),
    ]
