# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='content',
            field=models.CharField(max_length=800),
        ),
    ]
